#!/usr/bin/env bash
set -euo pipefail

: "${GOOGLE_CLOUD_PROJECT:?Set GOOGLE_CLOUD_PROJECT}"
: "${GOOGLE_CLOUD_REGION:=asia-southeast1}"
: "${CLOUD_RUN_SERVICE:=wanderlust-backend}"
: "${CLOUD_RUN_SERVICE_ACCOUNT:?Set CLOUD_RUN_SERVICE_ACCOUNT}"
: "${FIREBASE_PROJECT_ID:?Set FIREBASE_PROJECT_ID}"
: "${FIREBASE_WEB_API_KEY:?Set FIREBASE_WEB_API_KEY}"
: "${FIREBASE_IOS_BUNDLE_ID:?Set FIREBASE_IOS_BUNDLE_ID}"
: "${GOOGLE_IOS_CLIENT_ID:?Set GOOGLE_IOS_CLIENT_ID}"
: "${GOOGLE_IOS_REVERSED_CLIENT_ID:?Set GOOGLE_IOS_REVERSED_CLIENT_ID}"
: "${GOOGLE_SERVER_CLIENT_ID:?Set GOOGLE_SERVER_CLIENT_ID}"

IMAGE="gcr.io/${GOOGLE_CLOUD_PROJECT}/${CLOUD_RUN_SERVICE}:$(git rev-parse --short HEAD)"

gcloud builds submit --project "${GOOGLE_CLOUD_PROJECT}" --tag "${IMAGE}" .

gcloud run deploy "${CLOUD_RUN_SERVICE}" \
  --project "${GOOGLE_CLOUD_PROJECT}" \
  --region "${GOOGLE_CLOUD_REGION}" \
  --image "${IMAGE}" \
  --service-account "${CLOUD_RUN_SERVICE_ACCOUNT}" \
  --allow-unauthenticated \
  --set-env-vars "APP_ENV=production,APP_NAME=Wanderlust Trip Backend,GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT},GOOGLE_CLOUD_REGION=${GOOGLE_CLOUD_REGION},FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID},FIREBASE_WEB_API_KEY=${FIREBASE_WEB_API_KEY},FIREBASE_IOS_BUNDLE_ID=${FIREBASE_IOS_BUNDLE_ID},GOOGLE_IOS_CLIENT_ID=${GOOGLE_IOS_CLIENT_ID},GOOGLE_IOS_REVERSED_CLIENT_ID=${GOOGLE_IOS_REVERSED_CLIENT_ID},GOOGLE_SERVER_CLIENT_ID=${GOOGLE_SERVER_CLIENT_ID},USE_VERTEX_AI=true,VERTEX_AI_LOCATION=${GOOGLE_CLOUD_REGION},FIRESTORE_DATABASE_ID=(default),PUBSUB_LOCATION_EVENTS_TOPIC=location-events,PUBSUB_AGENT_RUNS_TOPIC=agent-runs,PUBSUB_NOTIFICATIONS_TOPIC=notifications" \
  --set-secrets "GOOGLE_MAPS_BACKEND_API_KEY=google-maps-backend-api-key:latest"

gcloud run services describe "${CLOUD_RUN_SERVICE}" \
  --project "${GOOGLE_CLOUD_PROJECT}" \
  --region "${GOOGLE_CLOUD_REGION}" \
  --format 'value(status.url)'
